#!/bin/python

import sys
from git import Repo
import os

repo = Repo(os.getcwd())

assert os.path.exists(sys.argv[1]), "No file to change the commit of"
message_file = sys.argv[1]



branch = repo.active_branch.name
slash_split = branch.split('/')
branch_type = slash_split[0].strip()

if branch_type in {'feature', 'hotfix', 'release', 'support'}:
	try:
		dash_split = slash_split[1].split('-')
		project    = dash_split [0].strip().upper()
		sha        = dash_split [1].strip().lower()

		message = ''
		with open(message_file, 'r') as file: message = file.read()
		with open(message_file, 'w') as file: file.write("[{}-{}] {}".format(project, sha, message))
	except:
		pass
