#!/bin/python

import sys
from git import Repo
import os
import re

repo = Repo(os.getcwd())

assert os.path.exists(sys.argv[1]), "No file to change the commit of"
message_file = sys.argv[1]


exp = r'(feature|hotfix|release|support)/([A-Z]+)-([a-z0-9]+).*'

match = re.search(exp,repo.active_branch.name)

if match:
	try:
		project = match.group(2)
		sha     = match.group(3)
		message = None
		with open(message_file, 'r') as f:
			message = f.read()
		with open(message_file, 'w') as f:
			f.write("[{}-{}] {}".format(project, sha, message))
	except:
		print "Couldn't write to file"
